### ISSUE TITLE
Add NGRX state managements in the app

### ISSUE THREAD

**Issue by Mahmoudibrahim03** [jm2097/angular-boilerplate#646]
**Is your feature request related to a problem? Please describe.**
No, But it will help within large-scale projects

**Describe the solution you'd like**
integrate and add NGRX configuration

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03,

There are quite a few state management libraries for Angular. I'm kinda partial to [elf](https://ngneat.github.io/elf/). However, I usually don't bother with a state management solution if the project's complexity doesn't call for it.

With that being said, I believe the best way to implement this feature in a starter template like this is to create different forks with different possibilities (e,g,. **angular-boilerplate-ngrx**, **angular-boilerplate-ngxs**, **angular-boilerplate-akita**, etc.).

Another option would be to create different setup scripts under the [/scripts](https://github.com/juanmesa2097/angular-boilerplate/tree/main/scripts) folder (e,g,. `setup_ngrx.sh`, `setup_ngxs.sh`, `setup_akita.sh`, etc.).

Lastly, another option I can think of is to create different branches for each option, but I personally don't like it because it would be challenging to keep everything updated.

What do you think?
---

**Comment by Mahmoudibrahim03** [comment]
@juanmesa2097 

I agree with you 
It will be cool if there is another repo handling complex (Big scale) project
which will include a State management solution and I think will need some changes like :
changing the boilerplate from application based with standalone components to modules to make it more suitable for the project scale and scalability  

I just took a quick look at [eIf](https://ngneat.github.io/elf/docs/store)  and I found it really interesting but NGRX is more popular and this variety of State management libs will let be the reason to make different kinds of boilerplates as you mentioned above  

**Are you agree?!**

**Comment by juanmesa2097** [comment]
@Mahmoudibrahim03 Yes, right now this project is focused on providing a generic and versatile starting point for projects of all sizes, so devs can start building quickly upon it. I agree that the best solution for this specific issue would be creating another repo that will be focused on full enterprise needs. It could contain state management, UI components library, considerable coverage on unit and E2E testing, a documentation portal, storybook, among other things. Personally, If I were to build a project with those characteristics using Angular, I'd probably use [analog](https://analogjs.org/) as the meta-framework.

About the NgModules, I believe the Angular team will deprecate them in the next major versions since components have become the default building blocks and it's recommended to avoid modules (or migrate) for this exact reason.
